#!/bin/bash

apt-get update
apt-get upgrade
apt-get -y install apt-transport-https wget curl unzip ca-certificates software-properties-common
cd /tmp

wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube-linux-amd64
mv minikube-linux-amd64 /usr/local/bin/minikube

curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x ./kubectl 
mv kubectl /usr/local/bin/

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
apt update
apt-cache policy docker-ce
apt install docker-ce
usermod -aG docker ubuntu

VERSION=$(curl -Ls https://github.com/helm/helm/releases/latest |grep 'href="/helm/helm/releases/tag/v3.' | grep -v no-underline  | cut -d '"' -f 2 | awk '{n=split($NF,a,"/");print a[n]}') 
curl -O https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz
tar xzvf helm-${VERSION}-linux-amd64.tar.gz
mv linux-amd64/helm /usr/local/bin
rm -rf linux-amd64
rm helm-${VERSION}-linux-amd64.tar.gz

minikube start --vm-driver=none
minikube status

echo "Congratulations!"
echo "You can try something like:"
echo "kubectl get pods --all-namespaces"
echo "kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10"
echo "kubectl expose deployment hello-minikube --type=NodePort --port=8080"
echo "kubectl get pods --all-namespaces"
echo "minikube service hello-minikube --url"
